---
name: CI/CD - Production

on:
  workflow_dispatch: 
    inputs: {}


jobs:
  build:
    needs:
      - version-bump
    uses: ./.github/workflows/_build.yml
    with:
      is-release: true

  production-deploy:
    needs:
      - build
      - tag
    uses: ./.github/workflows/_deploy.yml
    secrets: inherit
    with:
      environment: production
      version: ${{ needs.build.outputs.version }}
