---
name: CI/CD - Production

on:
  workflow_dispatch: 
    inputs: {}


jobs:
  build:
    needs:
      - version-bump
    uses: ./.github/workflows/_build.yml
      with:
        version-bump: true

  tag:
    name: Create Tag
    runs-on: ubuntu-22.04
    needs:
      - build
    steps:
      - name: Prep for Release
        run: |
          echo "Creating GitHub tag..."
          echo "  Create GitHub tag from local source version"
          echo "Done"

  staging-deploy:
    needs:
      - build
      - tag
    uses: ./.github/workflows/_deploy.yml
    secrets: inherit
    with:
      environment: production
      version: ${{ needs.build.outputs.version }}
