---
name: CI/CD - Staging

on:
  workflow_dispatch: 
    inputs: {}
  push:
    branches:
      - main


jobs:
  build:
    uses: ./.github/workflows/_build.yml
    with:
      sha: ${{ github.sha }}

  staging-deploy:
    needs:
      - build
    uses: ./.github/workflows/_deploy.yml
    secrets: inherit
    with:
      environment: staging
      version: ${{ needs.build.outputs.version }}

  #production-deploy:
  #  needs:
  #    - build
  #  uses: ./.github/workflows/_deploy.yml
  #  secrets: inherit
  #  with:
  #    environment: staging
